### ISSUE TITLE
Style(Linting/Formatting): Add ESLint and Prettier to Acceptance Tests

### ISSUE THREAD

**Issue by ananaso** [justinthelaw/opera#110]
**Is your feature request related to a problem? Please describe.**
Following the conclusion of Issue #100, all linting and formatting has been isolated to `client` and thus leaves `acceptance` without linting and formatting. This leaves `acceptance` open to competing linting and formatting styles as different contributors work on them.

**Describe the solution you'd like**
Configure `acceptance` subproject to have ESLint and Prettier, restore the linting commands from the client `package.json` to the root `package.json`, and extend these commands to operate in client and acceptance. 

**Additional context**
Configuration files for ESLint and Prettier should match what's already in `client`. If possible, possibly point `acceptance` configuration to those files so that all linting and formatting configuration can be done in one spot?

**Comment by justinthelaw** [comment]
Modify the .prettierrc.json and .eslintec.json in the acceptance directory to match the client directory's .prettierrc.json and .eslintec.json. 

Ensure that the GitHub Actions under test-pipeline.yaml pass. There is an error with the npm run lint:all command, and more specifically the lint:acceptance command and execution.
